### ISSUE TITLE
Observable interface for subject

### ISSUE THREAD

**Issue by sdelaysam** [ddinu/observable#27]
Hi, @ddinu 

Is there a way to expose subject as pure observable?
Would be great to have "read-only" interface for subject (hiding `subject::notify()` and `value::set()`). 
Similar to Rx's `asObservable()`

**Comment by ddinu** [comment]
Right now, `subject` and `value` are not related, but they do have the same `subscribe(...)` method (this was by design).

An interface for both of them would be easy enough to implement, but these types are not meant to be polymorphic. I'll have to think about this a little more.

Edit: if you're willing to use templates, and ignore the mutating methods, subject and value could be used interchangeably in some cases.

**Comment by sdelaysam** [comment]
Probably it can be achieved using `subject<ObserverType, EnclosingType>` and `value<ObserverType, EnclosingType>`?  Hiding modifiers is quite ok for me.
